-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: fix-encoding-pragma
    -   id: name-tests-test
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.0.4
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.2
    hooks:
    -   id: reorder-python-imports
